services:
  timetable-app:
    build: .
    container_name: timetable-app
    ports:
      - "8003:80"
    volumes:
      - ./.env:/var/www/html/.env
    depends_on:
      - timetable-db
    restart: always
    networks:
      - default
      - school-net

  timetable-db:
    image: mysql:8
    container_name: timetable-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: School1234
      MYSQL_DATABASE: timetable
      MYSQL_USER: timetable_user
      MYSQL_PASSWORD: School1234
    volumes:
      - timetable_db_data:/var/lib/mysql
    networks:
      - default

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: timetable-phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: timetable-db
    depends_on:
      - timetable-db
    networks:
      - default

volumes:
  timetable_db_data:

networks:
  default:
  school-net:
    external: true
