services:
  timetable-app:
    build: .
    container_name: timetable-app
    ports:
      - "8080:80"
    volumes:
      - /home/sukhon_server/timetable/.env:/var/www/html/.env
    depends_on:
      - timetable-db
    restart: always

  timetable-db:
    image: mysql:8
    container_name: timetable-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: School1234
      MYSQL_DATABASE: timetable
      MYSQL_USER: timetable_user
      MYSQL_PASSWORD: School1234
    volumes:
      - timetable_db_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: timetable-phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: timetable-db
    depends_on:
      - timetable-db
volumes:
  timetable_db_data:
